"""Training-side building blocks for SwiftVR."""

from .checkpoint import (
    capture_trainable_parameters,
    cast_trainable_parameters,
    load_delta_checkpoint,
    parameter_update_summary,
    save_delta_checkpoint,
    trainable_named_parameters,
)
from .forward import (
    SwiftVRTrainingForward,
    WanShiftWindow2DTrainProcessor,
    decode_reae_clip,
    encode_reae_clip,
    forward_prompt_free_no_time_training,
    prepare_prompt_free_no_time_transformer_for_training,
    prepare_training_batch,
    required_pixel_multiple,
)
from .loop import (
    TrainingCursor,
    append_jsonl,
    build_fp32_adamw,
    build_grad_scaler,
    capture_rng_state,
    load_trainer_state,
    optimizer_state_summary,
    resolve_resume_checkpoint,
    restore_rng_state,
    save_trainer_state,
    seed_everything,
    skip_batches,
    write_latest_checkpoint,
)
from .stage3 import (
    VideoMetricAccumulator,
    advance_cursor_batches,
    stage3_reconstruction_objective,
    temporal_difference_mse,
    video_ssim,
)

__all__ = [
    "SwiftVRTrainingForward",
    "TrainingCursor",
    "VideoMetricAccumulator",
    "WanShiftWindow2DTrainProcessor",
    "advance_cursor_batches",
    "append_jsonl",
    "build_fp32_adamw",
    "build_grad_scaler",
    "capture_rng_state",
    "capture_trainable_parameters",
    "cast_trainable_parameters",
    "decode_reae_clip",
    "encode_reae_clip",
    "forward_prompt_free_no_time_training",
    "load_delta_checkpoint",
    "load_trainer_state",
    "optimizer_state_summary",
    "parameter_update_summary",
    "prepare_prompt_free_no_time_transformer_for_training",
    "prepare_training_batch",
    "required_pixel_multiple",
    "resolve_resume_checkpoint",
    "restore_rng_state",
    "save_delta_checkpoint",
    "save_trainer_state",
    "seed_everything",
    "skip_batches",
    "stage3_reconstruction_objective",
    "temporal_difference_mse",
    "trainable_named_parameters",
    "video_ssim",
    "write_latest_checkpoint",
]
